name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  validate:
    name: Validate renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Validate
        uses: rinchsan/renovate-config-validator@b87b6441b539cd7bcf6e684fb6cac65b81e84085 # tag=v0.0.10
        with:
          pattern: '*.json'
