name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  validate:
    name: Validate renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Validate
        uses: rinchsan/renovate-config-validator@fb9b41c5e259e46902369fc06f8c23f6453a82c6 # renovate: tag=v0.0.8
        with:
          pattern: '*.json'
